<?php


namespace app\utilities;


use yii\base\Module;

class SecondModule extends Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->modules = [
            'thirdlevel' => [
                'class' => 'app\utilities\ThirdModule',
                'basePath' => '@app'
            ]
        ];
    }

}